~/.../assignments/09_blastomatic$ chmod +x blastomatic.py
~/.../assignments/09_blastomatic$ make test
pytest -xv test.py blastomatic.py
================================================================================================================================ test session starts =================================================================================================================================
platform linux -- Python 3.12.7, pytest-8.3.4, pluggy-1.5.0 -- /nix/store/nqlc7ymyglrsfx1hlssssq6zzy0hmk2c-python-wrapped-0.1.0/bin/python3
cachedir: .pytest_cache
rootdir: /home/runner/workspace/assignments/09_blastomatic
plugins: pylint-0.21.0, mypy-0.10.3, flake8-1.3.0
collected 8 items                                                                                                                                                                                                                                                                    

test.py::test_exists PASSED                                                                                                                                                                                                                                                    [ 12%]
test.py::test_usage PASSED                                                                                                                                                                                                                                                     [ 25%]
test.py::test_bad_annotations PASSED                                                                                                                                                                                                                                           [ 37%]
test.py::test_bad_input_file PASSED                                                                                                                                                                                                                                            [ 50%]
test.py::test_good_input FAILED                                                                                                                                                                                                                                                [ 62%]

====================================================================================================================================== FAILURES ======================================================================================================================================
__________________________________________________________________________________________________________________________________ test_good_input ___________________________________________________________________________________________________________________________________

    def test_good_input() -> None:
        """ Works on good input """
    
        outfile = 'out.csv'
        if os.path.isfile(outfile):
            os.remove(outfile)
    
        try:
            cmd = f'{PRG} -a {META} -b {HITS1}'
            print(cmd)
            rv, out = getstatusoutput(cmd)
>           assert rv == 0
E           assert 1 == 0

test.py:66: AssertionError
-------------------------------------------------------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------------------------------------------------------
./blastomatic.py -a ./inputs/meta.csv -b ./inputs/hits1.csv
============================================================================================================================== short test summary info ===============================================================================================================================
FAILED test.py::test_good_input - assert 1 == 0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================================================================ 1 failed, 4 passed in 0.45s =============================================================================================================================
make: *** [Makefile:4: test] Error 1